### ISSUE TITLE
Check if the audio listener setup is correct.

### ISSUE THREAD

**Issue by cai-mobfish** [mobfishgmbh/Cardboard-VR-Unity-SDK#37]
## Detail

This is a multi-camera setup, we need to make sure audio listener is still functional as expected.

## Tasks

- [x] Find a free music or audio, or self record one, add it into demo scene. Possible source: https://freemusicarchive.org/static
- [x] Setup a moving AudioSource, and mark it as spatial. Check if the audio effect is correct.
- [x] Update license, and readme for it.

**Comment by cai-mobfish** [comment]
Music is under Public Domain License.

https://freemusicarchive.org/music/Monplaisir/Heat_of_the_Summer/Monplaisir_-_Monplaisir_-_Heat_of_the_Summer_-_11_Estampe_Galactus_Barbare_Epaul_Giraffe_Ennui

AudioSource can't be marked as spatial because it needs proper audio spatializer. But 3D effect in AudioSource is enabled, and the audio effect is correct on iOS.
