### ISSUE TITLE
Editor plugin mockup

### ISSUE THREAD

**Issue by cai-mobfish** [mobfishgmbh/Cardboard-VR-Unity-SDK#4]
## Description

Without native plugin, the whole cardboard codes won't work and project won't run in Editor. We need mockup in Editor so that we can test some cases faster.

## Tasks

- [x] Keyboard Simulating head rotation
- [x] Left/Right eye camera view matrix for editor
- [x] eye mesh for editor mode

**Comment by cai-mobfish** [comment]
Press and hold left alt, then move mouse to rotate the camera.  
Press and hold left ctrl, then move mouse to tilt the camera.
